os: osx
osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1

jobs:
  include:
    - stage: test
      env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake
      before_install:
        - ./scripts/before_install_cmake.sh
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD

    - stage: test
      env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=asan
      before_install:
        - ./scripts/before_install_cmake.sh
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD $SANITIZERS

    - stage: test
      env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=tsan
      before_install:
        - ./scripts/before_install_cmake.sh
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD $SANITIZERS

    - stage: test
      env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=ubsan
      before_install:
        - ./scripts/before_install_cmake.sh
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD $SANITIZERS

  allow_failures:
    - env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=asan
    - env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=tsan
    - env: PROJECT=Firestore PLATFORM=macOS METHOD=cmake SANITIZERS=ubsan

branches:
  only:
    - master
