os: osx
osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1

jobs:
  include:
    - stage: checks
      # This only needs to be run once, so restrict it to an arbitrary combination
      before_install:
        - brew install clang-format
        - brew install swiftformat
      script:
        - ./scripts/check_whitespace.sh
        - ./scripts/check_copyright.sh
        - ./scripts/check_no_module_imports.sh
        - ./scripts/style.sh test-only $TRAVIS_COMMIT_RANGE
        # Google C++ style compliance
        - ./scripts/lint.sh $TRAVIS_COMMIT_RANGE

    - stage: test
      env:
        - PROJECT=Firestore PLATFORM=iOS METHOD=xcodebuild
      before_install:
        - bundle install
        - gem install xcpretty
        - ./scripts/if_changed.sh bundle exec pod install --project-directory=Firestore/Example --repo-update
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD

    - stage: test
      env:
        - PROJECT=Firestore PLATFORM=macOS METHOD=cmake
      before_install:
        - bundle install
        - gem install xcpretty
        - brew install cmake
        - brew install go # Somehow the build for Abseil requires this.
        - ./scripts/if_changed.sh bundle exec pod install --project-directory=Example --repo-update
        - ./scripts/if_changed.sh bundle exec pod install --project-directory=Firestore/Example --no-repo-update
      script:
        - ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM $METHOD

branches:
  only:
    - master
